# Generated by Django 6.0.5 on 2026-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working here', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Bullet points describing responsibilities, separate by newlines or JSON')),
                ('order', models.IntegerField(default=0, help_text='Sort order for timeline')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated list of tech stacks, e.g., React, Django, PostgreSQL', max_length=500)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Link to hosting image or public image asset', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Sort order for listing projects in frontend')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Tools/Others', 'Tools/Others')], max_length=50)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency percentage from 0 to 100')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
