# Generated by Django 6.0.5 on 2026-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_progress',
            field=models.IntegerField(default=100, help_text='Percentage progress from 0 to 100'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Planning', 'Planning')], default='Completed', max_length=50),
        ),
    ]
